name: Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Syntax Check (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linters
        run: |
          pip install flake8 bandit

      - name: Run flake8 syntax check
        run: flake8 .

      - name: Run Bandit security check
        run: bandit -r .
